server_connect_timeout: 5000
listeners:
- query_port: 25565
  motd: '&1JamesServerWaitQueue'
  tab_list: SERVER
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    0.0.0.0: queue
  ping_passthrough: false
  priorities:
  - target
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 0
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: null
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.find
  - bungeecord.command.server
  - bungeecord.command.list
log_pings: false
connection_throttle_limit: 3
prevent_proxy_connections: true
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  jameshackerbond:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 00000-0-000-00000
online_mode: true
forge_support: true
disabled_commands:
- bungeecord.command.server
servers:
  target:
    motd: '&eYOUR SERVER TARGET HERE'
    address: 0.0.0.0:25565
    restricted: true
  queue:
    motd: '&eYOUR SERVER QUEUE HERE'
    address: 0.0.0.0:25572
    restricted: false
